# Generated by Django 3.2.14 on 2022-09-10 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('textdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='content',
            field=models.CharField(default=datetime.datetime(2022, 9, 10, 11, 34, 41, 316041, tzinfo=utc), max_length=125),
            preserve_default=False,
        ),
    ]
